---
title: "Assignment_6"
author: "Abderezzak Amimer"
date: "09/04/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survival)
library(randomForestSRC)
library(uplift)
```

### Problem 1

#### Question 1
```{r}
load("uplift.RData")

# Training with two model approach using a logistic regression

#model 1 : with treatment = 1
glm_1 <- glm(PURCHASE ~ . -TREATMENT , data = uplift.train[which(uplift.train$TREATMENT == 1 ) , ] , family = "binomial")

#model 2 : with treatment = 0
glm_0 <- glm(PURCHASE ~ . -TREATMENT , data = uplift.train[which(uplift.train$TREATMENT == 0 ) , ] , family = "binomial")

#Predicting on the test set with model 1
pred_glm_1 <- predict(glm_1 , newdata = uplift.test , type="response")

#Predicting on the test set with model 2
pred_glm_0 <- predict(glm_0 , newdata=uplift.test , type="response")

#Lift calculation
lift_2models <- pred_glm_1 - pred_glm_0

#Print the lift of the top 10 subjects
tail(sort(lift_2models) , 10)
```


#### Question 2

```{r}
### Using a tree based approach

uprf=upliftRF(PURCHASE ~.+trt(TREATMENT), data=uplift.train,split_method ="ED",ntree=100)

preduprf=predict(uprf,newdata=uplift.test)

liftuprf=preduprf[,1]-preduprf[,2]


# Comparing the rank of both
ranking <- seq(1 , length(lift_2models) , 1)

# creating an arbitrary id
id <- seq(1 , length(lift_2models) , 1 )

# binding the id
liftuprf_rank <- as.data.frame(cbind(id , liftuprf))
lift_2models_rank <- as.data.frame(cbind(id , lift_2models))

# ordering them
lift_2models_rank <- lift_2models_rank[order(lift_2models_rank$lift_2models , decreasing = TRUE) , ]
liftuprf_rank <- liftuprf_rank[order(liftuprf_rank$liftuprf , decreasing = TRUE) , ]

# append the rank
lift_2models_rank$rank2 <- ranking
liftuprf_rank$rank <- ranking


#Merging the data set and plotting the ranking
rank_data <- merge(lift_2models_rank , liftuprf_rank , by="id" )


# Plot to compare the ranking
par(cex.axis=0.75 , cex.main=0.85 , cex.lab=0.85)
plot(rank_data$rank , rank_data$rank2,
main= "Ranking of perdicted lift from a tree based approach against the lift from a two model approach",
xlab= "Ranking from a tree based approach",
ylab= "Ranking from a two model approach")
```

#### Question 3 

```{r}
#Class tansformation approach
uplift.train_z <- uplift.train
uplift.train_z$z <- factor(((uplift.train_z$PURCHASE == uplift.train_z$TREATMENT)))

#Logistic
class_logistic <- glm(z ~ . -TREATMENT - PURCHASE, data=uplift.train_z , family = "binomial")
pred_class_logistic <- 2 * predict(class_logistic , newdata = uplift.test , type = "response") - 1 

#Tree based approache
class_rf <- rfsrc(z~. - TREATMENT - PURCHASE , data = uplift.train_z , ntree = 100)
pred_class_rf <- 2*predict(class_rf , newdata = uplift.test)$predicted[,2]-1

# ranking

# binding the id
class_log_rank <- as.data.frame(cbind(id ,pred_class_logistic ))
class_rf_rank <- as.data.frame(cbind(id , pred_class_rf))

# ordering them
class_log_rank <- class_log_rank[order(class_log_rank$pred_class_logistic , decreasing = TRUE) , ]
class_rf_rank <- class_rf_rank[order(class_rf_rank$pred_class_rf , decreasing = TRUE) , ]

# append the rank
class_log_rank$rank <- ranking
class_rf_rank$rank2 <- ranking


#Merging the data set and plotting the ranking
rank_data_2 <- merge(class_log_rank , class_rf_rank , by="id" )


# Plot to compare the ranking
par(cex.axis=0.75 , cex.main=0.85 , cex.lab=0.85)
plot(rank_data_2$rank2 , rank_data_2$rank,
main= "Comparing ranks of predicted lift from a class transformation approach using two different models",
xlab= "Ranking from a random forest model",
ylab= "Ranking from a logistic model")
```

#### Question 4
```{r}
# model 1 : 2 model approach
perf_2models <- performance(pred_glm_1 , pred_glm_0 , uplift.test$PURCHASE , uplift.test$TREATMENT )
q_2models <- qini(perf_2models , plotit = FALSE)

# Model 2 : tree based approach
perf_uprf <- performance(preduprf[,1] , preduprf[,2] , uplift.test$PURCHASE , uplift.test$TREATMENT)
q_uprf <- qini(perf_uprf , plotit=FALSE)

# Model 3 : Class with logistic reg
pref_class_log <- performance(rep(1 , length(pred_class_logistic)),
                              rep(1 , length(pred_class_logistic)) - pred_class_logistic, uplift.test$PURCHASE , uplift.test$TREATMENT)
q_class_log <- qini(pref_class_log, plotit = FALSE)

# Model 4 : Class with 
pref_class_rf <- performance(rep(1 , length(pred_class_rf)),
                              rep(1 , length(pred_class_rf)) - pred_class_rf, uplift.test$PURCHASE , uplift.test$TREATMENT)
q_class_rf <- qini(pref_class_rf, plotit = FALSE)

print(c(q_2models$Qini , q_uprf$Qini , q_class_log$Qini , q_class_rf$Qini))
```

### Question 5
Comments on the results

### Problem 2

#### Question 1

#### Question 2